config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :recipes
root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :user

	has_many :ingredients
	has_many :directions

	has_attached_file :image, styles: { medium: "400x400#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	accepts_nested_attributes_for :ingredients, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
	accepts_nested_attributes_for :directions, reject_if: proc { |attributes| attributes['step'].blank? }, allow_destroy: true
	
	validates :title, :description, :image, presence: true
	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)
		if @recipe.save
			redirect_to @recipe, notice: "Successfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end

	private 

		def find_recipe
			@recipe = Recipe.find(params[:id])
		end

		def recipe_params
			params.require(:recipe).permit(:title, :description, :image, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_nav.html.erb
<nav>
	<div class="nav-wrapper grey lighten-1">
		<!-- <div class="container"> -->
			<%= link_to "Recipe Box", root_path, class: "brand-logo " %>
			<% if user_signed_in? %>
				<ul class="right">
					<li><%= link_to "Recipe", new_recipe_path %></li>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				</ul>
			<% else %>
				<ul class="right">
					<li><%= link_to "Sign In", new_user_session_path %></li>
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
				</ul>
			<% end %>
		<!-- </div> -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <br>
    <div class="container">
      <% flash.each do |name, msg| %>
        <div class="alert">
          <%= content_tag :div, msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
	<div class="nested-fields">
		<%= f.input :step, wrapper_html: {class: "m6 s12"} %>
		<%= link_to_remove_association "Remove", f, class: "right-align btn" %>
	</div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: {multipart: true} do |f| %>
	<% if @recipe.errors.any? %>
		<div id="errors">
			<p><%= @recipe.errors.count %> Prevented this recipe from saving</p>
			<ul>
				<% @recipe.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="panel-body">
		<div class="row">
			<%= f.input :title, wrapper_html: { class: "m6 s12" } %>
			<%= f.input :description, wrapper_html: { class: "materialize-textarea  s12" } %>
		</div>
		  <div class="#">
	         <div class="file-field input-field gallery_picture">
	        	<div class="btn">
		          <span>Upload file</span>
		          <%= f.input_field :image %>
	          	</div>
	        	<input class="file-path validate" type="text"/>
	        </div>
	    </div>
		

		<div class="row">
			<div class="col s6">
				<h3>Ingredients</h3>
				<div id="ingredients">
					<%= f.simple_fields_for :ingredients do |ingredient| %>
						<%= render 'ingredient_fields', f: ingredient %>
					<% end %>
					<div class="links">
						<%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn add_button" %>
					</div>
				</div>
			</div>
			<div class="col s6">
				<h3>Directions</h3>
				<div id="directions">
					<%= f.simple_fields_for :directions do |direction| %>
						<%= render 'direction_fields', f: direction %>
					<% end %>
					<div class="links">
						<%= link_to_add_association 'Add Step', f, :directions, class: "btn add_button" %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<%= f.button :submit, class: 'btn waves-effect waves-light' %>
	<%= link_to "back", root_path, class: "waves-effect waves-light btn" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
	<div class="nested-fields">
		<%= f.input :name, input_html: {class: "form-input form-control"} %>
		<%= link_to_remove_association "Remove", f, class: "right-align btn" %>
	</div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>
<br>

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
	<div class="row">
		<% recipes.each do |recipe| %>
			<div class="col s4">
				<div class="card hoverable">
					<div class="card-image ">
						<%= link_to recipe do %>
							<%= image_tag recipe.image.url(:medium, class: "recipe_image") %>
						<% end %>
						<span class="card-title">Card Title</span>
						<a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons">chat</i></a>
					</div>
					<div class="card-content">
						<h5 class=" red-text text-red"><%= link_to recipe.title, recipe %></h5>	
					</div>
				</div>
			</div>
		<% end %>
	</div>
<% end %>





	

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<br>
<br>

app/views/recipes/show.html.erb
<div class="main_content">
	<div id="recipe_top" class="row">
		<div class="col s4 ">
			<%= image_tag @recipe.image.url(:medium, class: "recipe_image") %>
		</div>
		<div class="col s7 push-s1">
			<div id="recipe_info">
				<h1><%= @recipe.title %></h1>
				<p class="description">
					<%= @recipe.description %>
				</p>
				<p>Submited by <%= @recipe.user.email %></p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col s6">
			<div id="ingredients">
				<h2>Ingedients</h2>
				<ul>
					<% @recipe.ingredients.each do |ingredient| %>
						<li><%= ingredient.name %></li>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="col s6">
			<div id="directions">
				<h2>Directions</h2>
				<ul>
					<% @recipe.directions.each do |direction| %>
						<li><%= direction.step %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col s12">
			<%= link_to "Back", root_path, class: "btn" %>
			<% if user_signed_in? %>
				<%= link_to "Edit", edit_recipe_path, class: "btn" %>
				<%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure"},class: "btn" %>
			<% end %>
		</div>
	</div>
</div>